use_frameworks!

platform :ios, '8.0'

target 'fb2sql-ios_Example' do
  pod 'SQLDatabase', :path => '../'
  pod "AFNetworking", "~> 2.7"


  target 'fb2sql-ios_Tests' do
    inherit! :search_paths

    
  end
end
